version: '3'
services:
  spl-backed:
    build: .
    env_file: .env
    image: spl-backend
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "3000:3000"
    volumes:
      - '.:/app'
    networks:
      - spl-network
    depends_on:
      - spl-mysql
      - spl-redis
  spl-mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - spl-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
  spl-redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis:/data'
    networks:
      - spl-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
  family-phpmyadmin:
    depends_on:
      - spl-mysql
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: '${DB_HOST}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    networks:
      - spl-network
networks:
  spl-network:
    driver: bridge
volumes:
  mysql:
    driver: local
  redis:
    driver: local
